### ISSUE TITLE
skool2asm: create default labels for referenced memory areas

### ISSUE THREAD

**Issue by vmorilla** [skoolkid/skoolkit#115]
It would be really nice if SkoolKit might create default labels not only for instructions, but for memory areas referenced in the code. For instance:
```
; Data block 
b$5d7a defb $10,$06,$97,$92,$95,$95,$95,$95

; Routine
c$5d9d xor a         ;
 $5da5 ld ($5d7a),a  ;
```
would produce:
```
L5d7a:
    defb $10,$06,$97,$92,$95,$95,$95,$95

L5d9d:
  xor a
  ld (L5d7a),a
```
My motivation is this: I'm working on a reissue of an old game I did in the 80s. I just keep the tape files (no assemblies). Nevertheless, I remember doing patchwork with my cassette in order to fit all the code in the memory available. With modern new cross-assemblers, it would be nice to reallocate the code and organise it a little bit better. 

Thanks a lot for your work!

**Comment by skoolkid** [comment]
This is actually partially possible (by accident) already, via the `SnapshotReferenceOperations` parameter in the `[skoolkit]` section of *skoolkit.ini*:

    SnapshotReferenceOperations=DJ,JR,JP,CA,RS,LD (

This would treat instructions that start with `LD (` (in addition to the regular jump and call instructions) as referrers, and make `sna2skool.py` mark the addresses they refer to with `*`, which in turn means they can then be given default labels by `skool2asm.py` and `skoolhtml.py`.

I'll add full support for doing this in 8.5, probably by allowing regular expressions in `SnapshotReferenceOperations`.

I'll also look at making the format of default labels configurable, so you can have `L5d7a` (for example) instead of something like `L5d62_12`.

**Comment by skoolkid** [comment]
After 130fa6b01405652180f5c8a6c2a16857fa3093ae and 3fffb9c695d957cae31406cd3423c13b00ee7e81, you can now designate 'LD r,(nn)' and 'LD (nn),r' as instructions whose address operands identify entry points (in addition to the jump and call instructions), via the `SnapshotReferenceOperations` parameter in the `[skoolkit]` section of *skoolkit.ini*:

    [skoolkit]
    SnapshotReferenceOperations=;DJ;JR;JP;CA;RS;LD \(\i\);LD .*,\(\i\)

With this change in place, `sna2skool.py` will mark addresses referred to by 'LD r,(nn)' and 'LD (nn),r' instructions as entry points (i.e. place an asterisk beside them in the skool file). Then the `--create-labels` option of `skool2asm.py` will create default labels for these marked addresses.

**Comment by skoolkid** [comment]
And now with 9b6123bca0ce9fefd43244bac97d61b46aa926f2 in place, you can specify the format of the default labels created by skool2asm.py via the `EntryLabel` and `EntryPointLabel` configuration parameters. So putting all this together:

```
[skoolkit]
SnapshotReferenceOperations=;DJ;JR;JP;CA;RS;LD \(\i\);LD .*,\(\i\)

[skool2asm]
EntryLabel=L{address}
EntryPointLabel=L{address}
```

This configuration will make `skool2asm.py` create default labels like `L5d7a` for all unlabelled instructions (assuming the instruction addresses in the skool file are in lower case hexadecimal).
